name: twilio_dart
version: 0.0.6
author: Marcos Placona <hi@placona.co.uk>
description: An implementation of the Twilio API for Dart.
homepage: http://mplacona.github.io/twilio-dart
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  http: any
dev_dependencies:
  browser: '>=0.10.0 <=0.10.0+2'
  mock: any
  unittest: any
